version: '3.5'

volumes:
  postgres:
    name: teamcity-postgres
  teamcity_data:
    name: teamcity-data

services:
  database:
    container_name: database-teamcity
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-0.0.0.0:5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-teamcity_db}
    volumes:
      - postgres:/var/lib/postgresql/data

  teamcity:
    container_name: teamcity-server
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION:-2023.05}
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    environment:
      TEAMCITY_CONTEXT: ${TEAMCITY_CONTEXT:-/}
    ports:
      - "${TEAMCITY_PORT:-0.0.0.0:8111}:8111"

  agent1:
    container_name: agent1-teamcity
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION:-2023.05}-linux-sudo
    restart: unless-stopped
    privileged: true
    environment:
      AGENT_NAME: Agent MarkI
      SERVER_URL: teamcity:8111${TEAMCITY_CONTEXT:-}
      DOCKER_IN_DOCKER: start
      AGENT_TOKEN: 71723e836df10d65390420820fe3451c

  agent2:
    container_name: agent2-teamcity
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION:-2023.05}-linux-sudo
    restart: unless-stopped
    privileged: true
    environment:
      AGENT_NAME: Agent MarkII
      SERVER_URL: teamcity:8111${TEAMCITY_CONTEXT:-}
      DOCKER_IN_DOCKER: start
      AGENT_TOKEN: 5881d299516ed1b39a3ce8c2dc05ee00
