version: '3.5'

volumes:
  postgres:
    name: teamcity-postgres
  teamcity_data:
    name: teamcity-data

services:
  database:
    container_name: database-teamcity
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-0.0.0.0:5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-teamcity_db}
    volumes:
      - postgres:/var/lib/postgresql/data

  teamcity:
    container_name: teamcity-server
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION:-2023.05}
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    environment:
      TEAMCITY_CONTEXT: ${TEAMCITY_CONTEXT:-/}
    ports:
      - "${TEAMCITY_PORT:-0.0.0.0:8111}:8111"

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION:-2023.05}-linux-sudo
    privileged: true
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      SERVER_URL: ${AGENT_SERVER_URL:-teamcity:8111}
      DOCKER_IN_DOCKER: start

  teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION:-2023.05}-linux-sudo
    privileged: true
    volumes:
      - ./agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      SERVER_URL: ${AGENT_SERVER_URL:-teamcity:8111}
      DOCKER_IN_DOCKER: start
